export default {
  "入门": [
    ["安装", "/docs/installation"],
    ["编辑器设置", "/docs/editor-setup"],
    ["兼容性", "/docs/compatibility"],
    ["升级指南", "/docs/upgrade-guide"],
  ] as const,
  "核心概念": [
    ["使用工具类设计样式", "/docs/styling-with-utility-classes"],
    ["悬停、聚焦及其他状态", "/docs/hover-focus-and-other-states"],
    ["响应式设计", "/docs/responsive-design"],
    ["暗黑模式", "/docs/dark-mode"],
    ["主题变量", "/docs/theme"],
    ["颜色", "/docs/colors"],
    ["添加自定义样式", "/docs/adding-custom-styles"],
    ["检测源文件中的类名", "/docs/detecting-classes-in-source-files"],
    ["函数与指令", "/docs/functions-and-directives"],
  ] as const,
  "基础样式": [["预处理", "/docs/preflight"]] as const,
  "布局": [
    ["宽高比", "/docs/aspect-ratio"],
    ["多列", "/docs/columns"],
    ["断行后", "/docs/break-after"],
    ["断行前", "/docs/break-before"],
    ["断行内", "/docs/break-inside"],
    ["盒子装饰断行", "/docs/box-decoration-break"],
    ["盒模型", "/docs/box-sizing"],
    ["显示", "/docs/display"],
    ["浮动", "/docs/float"],
    ["清除浮动", "/docs/clear"],
    ["隔离", "/docs/isolation"],
    ["对象适应", "/docs/object-fit"],
    ["对象位置", "/docs/object-position"],
    ["溢出", "/docs/overflow"],
    ["超滚行为", "/docs/overscroll-behavior"],
    ["定位", "/docs/position"],
    ["上 / 右 / 下 / 左", "/docs/top-right-bottom-left"],
    ["可见性", "/docs/visibility"],
    ["层级", "/docs/z-index"],
  ] as const,
  "弹性盒子与网格": [
    ["弹性基值", "/docs/flex-basis"],
    ["弹性布局方向", "/docs/flex-direction"],
    ["弹性换行", "/docs/flex-wrap"],
    ["弹性", "/docs/flex"],
    ["弹性增长", "/docs/flex-grow"],
    ["弹性收缩", "/docs/flex-shrink"],
    ["排列顺序", "/docs/order"],
    ["网格模板列", "/docs/grid-template-columns"],
    ["网格列", "/docs/grid-column"],
    ["网格模板行", "/docs/grid-template-rows"],
    ["网格行", "/docs/grid-row"],
    ["网格自动排列", "/docs/grid-auto-flow"],
    ["网格自动列", "/docs/grid-auto-columns"],
    ["网格自动行", "/docs/grid-auto-rows"],
    ["间隙", "/docs/gap"],
    ["内容对齐", "/docs/justify-content"],
    ["项目水平对齐", "/docs/justify-items"],
    ["自我水平对齐", "/docs/justify-self"],
    ["内容对齐", "/docs/align-content"],
    ["项目对齐", "/docs/align-items"],
    ["自我对齐", "/docs/align-self"],
    ["内容放置", "/docs/place-content"],
    ["项目放置", "/docs/place-items"],
    ["自我放置", "/docs/place-self"],
  ] as const,
  "间距": [
    ["内边距", "/docs/padding"],
    ["外边距", "/docs/margin"],
  ] as const,
  "尺寸": [
    ["宽度", "/docs/width"],
    ["最小宽度", "/docs/min-width"],
    ["最大宽度", "/docs/max-width"],
    ["高度", "/docs/height"],
    ["最小高度", "/docs/min-height"],
    ["最大高度", "/docs/max-height"],
    ["内联尺寸", "/docs/inline-size"],
    ["最小内联尺寸", "/docs/min-inline-size"],
    ["最大内联尺寸", "/docs/max-inline-size"],
    ["块尺寸", "/docs/block-size"],
    ["最小块尺寸", "/docs/min-block-size"],
    ["最大块尺寸", "/docs/max-block-size"],
  ] as const,
  "排版": [
    ["字体系列", "/docs/font-family"],
    ["字体大小", "/docs/font-size"],
    ["字体平滑", "/docs/font-smoothing"],
    ["字体风格", "/docs/font-style"],
    ["字体粗细", "/docs/font-weight"],
    ["字体拉伸", "/docs/font-stretch"],
    ["数字字体变体", "/docs/font-variant-numeric"],
    ["字体特性设置", "/docs/font-feature-settings"],
    ["字间距", "/docs/letter-spacing"],
    ["行数截断", "/docs/line-clamp"],
    ["行高", "/docs/line-height"],
    ["列表样式图片", "/docs/list-style-image"],
    ["列表样式位置", "/docs/list-style-position"],
    ["列表样式类型", "/docs/list-style-type"],
    ["文本对齐", "/docs/text-align"],
    ["颜色", "/docs/color"],
    ["文本装饰线", "/docs/text-decoration-line"],
    ["文本装饰颜色", "/docs/text-decoration-color"],
    ["文本装饰样式", "/docs/text-decoration-style"],
    ["文本装饰厚度", "/docs/text-decoration-thickness"],
    ["下划线偏移", "/docs/text-underline-offset"],
    ["文本转换", "/docs/text-transform"],
    ["文本溢出", "/docs/text-overflow"],
    ["文本换行", "/docs/text-wrap"],
    ["文本缩进", "/docs/text-indent"],
    ["垂直对齐", "/docs/vertical-align"],
    ["空白处理", "/docs/white-space"],
    ["单词断行", "/docs/word-break"],
    ["溢出换行", "/docs/overflow-wrap"],
    ["连字符", "/docs/hyphens"],
    ["内容", "/docs/content"],
  ] as const,
  "背景": [
    ["背景附着", "/docs/background-attachment"],
    ["背景裁剪", "/docs/background-clip"],
    ["背景颜色", "/docs/background-color"],
    ["背景图像", "/docs/background-image"],
    ["背景原点", "/docs/background-origin"],
    ["背景位置", "/docs/background-position"],
    ["背景重复", "/docs/background-repeat"],
    ["背景尺寸", "/docs/background-size"],
  ] as const,
  "边框": [
    ["边框圆角", "/docs/border-radius"],
    ["边框宽度", "/docs/border-width"],
    ["边框颜色", "/docs/border-color"],
    ["边框样式", "/docs/border-style"],
    ["轮廓宽度", "/docs/outline-width"],
    ["轮廓颜色", "/docs/outline-color"],
    ["轮廓样式", "/docs/outline-style"],
    ["轮廓偏移", "/docs/outline-offset"],
  ] as const,
  "效果": [
    ["盒子阴影", "/docs/box-shadow"],
    ["文本阴影", "/docs/text-shadow"],
    ["不透明度", "/docs/opacity"],
    ["混合模式", "/docs/mix-blend-mode"],
    ["背景混合模式", "/docs/background-blend-mode"],
    ["遮罩边界", "/docs/mask-clip"],
    ["遮罩组合", "/docs/mask-composite"],
    ["遮罩图像", "/docs/mask-image"],
    ["遮罩模式", "/docs/mask-mode"],
    ["遮罩来源", "/docs/mask-origin"],
    ["遮罩位置", "/docs/mask-position"],
    ["遮罩重复", "/docs/mask-repeat"],
    ["遮罩大小", "/docs/mask-size"],
    ["遮罩类型", "/docs/mask-type"],
  ] as const,
  "滤镜": [
    [
      "滤镜",
      "/docs/filter",
      [
        ["模糊", "/docs/filter-blur"],
        ["亮度", "/docs/filter-brightness"],
        ["对比度", "/docs/filter-contrast"],
        ["投影", "/docs/filter-drop-shadow"],
        ["灰度", "/docs/filter-grayscale"],
        ["色相旋转", "/docs/filter-hue-rotate"],
        ["反转", "/docs/filter-invert"],
        ["饱和", "/docs/filter-saturate"],
        ["复古", "/docs/filter-sepia"],
      ] as const,
    ] as const,
    [
      "背景滤镜",
      "/docs/backdrop-filter",
      [
        ["模糊", "/docs/backdrop-filter-blur"],
        ["亮度", "/docs/backdrop-filter-brightness"],
        ["对比度", "/docs/backdrop-filter-contrast"],
        ["灰度", "/docs/backdrop-filter-grayscale"],
        ["色相旋转", "/docs/backdrop-filter-hue-rotate"],
        ["反转", "/docs/backdrop-filter-invert"],
        ["不透明度", "/docs/backdrop-filter-opacity"],
        ["饱和", "/docs/backdrop-filter-saturate"],
        ["复古", "/docs/backdrop-filter-sepia"],
      ] as const,
    ] as const,
  ] as const,
  "表格": [
    ["边框合并", "/docs/border-collapse"],
    ["边框间距", "/docs/border-spacing"],
    ["表格布局", "/docs/table-layout"],
    ["表格标题位置", "/docs/caption-side"],
  ] as const,
  "过渡与动画": [
    ["过渡属性", "/docs/transition-property"],
    ["过渡行为", "/docs/transition-behavior"],
    ["过渡时长", "/docs/transition-duration"],
    ["过渡缓动函数", "/docs/transition-timing-function"],
    ["过渡延迟", "/docs/transition-delay"],
    ["动画", "/docs/animation"],
  ] as const,
  "变换": [
    ["背面可见性", "/docs/backface-visibility"],
    ["透视", "/docs/perspective"],
    ["透视原点", "/docs/perspective-origin"],
    ["旋转", "/docs/rotate"],
    ["缩放", "/docs/scale"],
    ["倾斜", "/docs/skew"],
    ["变换", "/docs/transform"],
    ["变换原点", "/docs/transform-origin"],
    ["变换样式", "/docs/transform-style"],
    ["平移", "/docs/translate"],
  ] as const,
  "交互": [
    ["强调色", "/docs/accent-color"],
    ["外观", "/docs/appearance"],
    ["插入符号颜色", "/docs/caret-color"],
    ["配色方案", "/docs/color-scheme"],
    ["光标", "/docs/cursor"],
    ["表单尺寸", "/docs/field-sizing"],
    ["指针事件", "/docs/pointer-events"],
    ["调整大小", "/docs/resize"],
    ["滚动行为", "/docs/scroll-behavior"],
    ["滚动边距", "/docs/scroll-margin"],
    ["滚动内边距", "/docs/scroll-padding"],
    ["滚动捕捉对齐", "/docs/scroll-snap-align"],
    ["滚动捕捉停止", "/docs/scroll-snap-stop"],
    ["滚动捕捉类型", "/docs/scroll-snap-type"],
    ["触控行为", "/docs/touch-action"],
    ["用户选择", "/docs/user-select"],
    ["即将改变", "/docs/will-change"],
  ] as const,
  "SVG": [
    ["填充", "/docs/fill"],
    ["描边", "/docs/stroke"],
    ["描边宽度", "/docs/stroke-width"],
  ] as const,
  "辅助功能": [["强制颜色调整", "/docs/forced-color-adjust"]] as const,
};
